QR2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
    path('', views.GamesIndexView.as_view(), name='index'),
    path('tag/', views.game_tag_entry, name='tag'),
    path('<int:gameID>/', views.game_items_index, name='gameIndex'),
    path('<int:gameID>/item/<int:itemID>/post/', views.module_item_post, name='modulePost'),
    path('<int:gameID>/render/<int:ID>/<str:is_cat>/', views.render_item, name='renderItem'),

# Adminpanel
    path('adminpanel/', views.adminpanel, name='adminpanel'),

    path('adminpanel/gamemaster/index/', views.GameMaster.Get_All.as_view(), name='gamemasterIndex'),
    path('adminpanel/gamemaster/panel/<int:gameID>/', views.GameMaster.GameMasterPanel.as_view(), name='gamemasterPanel'),
    path('adminpanel/gamemaster/Announce/', views.GameMaster.Announcement.as_view(), name='gamemasterPanelAnnounce'),
    path('adminpanel/gamemaster/finishbygm/', views.GameMaster.finishItemByGM.as_view(), name='gamemasterPanelFinishByGM'),
    path('adminpanel/games/Announce/', views.Games.Announcement.as_view(), name='makeAnnouncement'),
    path('adminpanel/games/', views.Games.Get_All.as_view(), name='adminpanelGames'),
    path('adminpanel/games/add/', views.Games.Add.as_view(), name='adminpanelGamesAdd'),
    path('adminpanel/games/delete/', views.Games.Delete.as_view(), name='adminpanelGamesDelete'),
    path('adminpanel/games/duplicate/', views.Games.Duplicate.as_view(), name='adminpanelGamesDuplicate'),
    path('adminpanel/games/<int:gameID>/', views.Games.Edit.as_view(), name='adminpanelGamesEdit'),
    path('adminpanel/games/publish/', views.Publish.Publish.as_view(), name='adminpanelGamesEditPublish'),
    path('adminpanel/games/item/finishbygm/', views.Games.finishItemByGM.as_view(), name='adminpanelItemFinishByGM'),
    path('adminpanel/games/<int:gameID>/category/<int:categoryID>/', views.Categories.Edit.as_view(), name='adminpanelGamesEditCategory'),
    path('adminpanel/categories/add/', views.Categories.Add.as_view(), name='adminpanelCategoriesAdd'),
    path('adminpanel/categories/delete/', views.Categories.Delete.as_view(), name='adminpanelCategoriesDelete'),
    path('adminpanel/categories/addItemConstruct', views.Items.AddInCategoryUrlScrubber.as_view(), name='adminpanelCategoriesAddItemConstruct'),
    path('adminpanel/categories/addItem/<str:typeID>/<int:categoryID>/<int:gameID>/', views.Items.AddInCategory.as_view(), name='adminpanelCategoriesAddItem'),
    path('adminpanel/categories/addExistingItem/', views.Items.AddExistingItemToCategory.as_view(), name='adminpanelCategoriesAddExistingItem'),
    path('adminpanel/modules/', views.AllItems.as_view(), name='adminpanelModules'),
    path('adminpanel/modules/<int:itemID>/', views.Items.EditItem.as_view(), name='adminpanelModulesEdit'),
    path('adminpanel/modules/addConstruct', views.Items.AddUrlScrubber.as_view(), name='adminpanelModulesAddItemConstruct'),
    path('adminpanel/modules/add/<str:typeID>/', views.Items.AddItem.as_view(), name='adminpanelModulesAddItem'),
    path('adminpanel/modules/delete/<int:itemID>/', views.Items.DeleteItem.as_view(), name='adminpanelModulesDelete'),

]

game/views/main_views.py
from datetime import timedelta
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.timezone import datetime
from django.views import generic
from django.db.models import Q
from django.contrib import messages

from game.models import Game, GameItemLink, Category
from game.core_control_methods.backend_socket_messenger import update_item
from game.running_rules import render_item_rules, post_item_rules
from QR2.settings import DEBUG


class GamesIndexView(generic.ListView):
    """
    List all the active games
    """
    template_name = 'game/index.html'
    context_object_name = 'activeGameList'

    def get_queryset(self):
        currentDateTime = datetime.now()
        now_plus_30mins = currentDateTime + timedelta(minutes=30)
        now_minus_30mins = currentDateTime - timedelta(minutes=30)

        if self.request.user.is_authenticated and self.request.user.is_staff:
            games = Game.objects.all()
        else:
            # Only display games that are both open and published and also are within a certain given time range (provided that it is time dependant)
            games = Game.objects.filter(published=True, accessThroughTag=False).filter(
                Q(noDateNorTime=True) | Q(noDateNorTime=False, startDateTime__lte=now_plus_30mins.astimezone(),
                                      endDateTime__gte=now_minus_30mins.astimezone()))

        return games.order_by('-publicationDate')


def is_game_accessable(request, gameID):
    """
    Check whether a game should still be accessible
    """
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    # For game debugging, gamemasters should be able to always join a game
    if request.user.is_authenticated and request.user.is_staff:
        return True

    try:
        game = Game.objects.get(gameID=gameID)
    except Game.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             'Het spel is niet gevonden!')
        messages.add_message(request, messages.DEBUG,
                             f'The exception <i>\'Game.DoesNotExist\'</i> occurred on id <i>\'{request.POST["id"]}\'</i>')
        return False

    # Game needs to be both open en published
    if game.published is False:
        return False

    currentDateTime = datetime.now()
    now_plus_30mins = currentDateTime + timedelta(minutes=30)
    now_minus_30mins = currentDateTime - timedelta(minutes=30)

    # Check whether game is still within time
    if game.noDateNorTime is False:
        if game.startDateTime >= now_plus_30mins.astimezone() or now_minus_30mins.astimezone() >= game.endDateTime:
            return False

    return True


def is_game_running(request, gameID):
    """
    Check whether a game should still be accessible
    """
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    # For game debugging, gamemasters should be able to always join a game
    if request.user.is_authenticated and request.user.is_staff:
        return True

    try:
        game = Game.objects.get(gameID=gameID)
    except Game.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             'Het spel is niet gevonden!')
        messages.add_message(request, messages.DEBUG,
                             f'The exception <i>\'Game.DoesNotExist\'</i> occurred on id <i>\'{request.POST["id"]}\'</i>')
        return False

    # Game needs to be both open en published
    if game.published is False or game.open is False:
        return False

    currentDateTime = datetime.now()

    # Check whether game is still within time
    if game.noDateNorTime is False:
        if game.startDateTime >= currentDateTime.astimezone() or currentDateTime.astimezone() >= game.endDateTime:
            return False

    return True


def game_tag_entry(request):
    if request.method == 'POST':
        if 'gameTag' in request.POST:
            try:
                game = Game.objects.get(accessTag=request.POST['gameTag'])
            except Game.DoesNotExist:
                messages.add_message(request, messages.ERROR,
                                     'Het spel is niet gevonden!')
                messages.add_message(request, messages.DEBUG,
                                     f'The exception <i>\'Game.DoesNotExist\'</i> occurred on accessTag <i>\'{request.POST["gameTag"]}\'</i>')
                return redirect('game:index')

            return redirect('game:gameIndex', gameID=game.gameID)
        else:
            # Problems with ID fetching
            messages.add_message(request, messages.ERROR,
                                 'Er ging iets mis met het invoeren van de gametag!')

            messages.add_message(request, messages.DEBUG,
                                 '<i>\'gameTag\'</i> is not in <i>\'request.POST\'</i>. Check your constructed form and post method.')

            return redirect('game:index')
    else:
        messages.add_message(request, messages.WARNING,
                             'Er ging iets mis met het invoeren van de gametag!')
        return redirect('game:index')

def game_items_index(request, gameID):
    if is_game_accessable(request, gameID) is False:
        messages.add_message(request, messages.INFO,
                             'Het spel is afgelopen!')
        return redirect('game:index')

    game_is_running = True
    if is_game_running(request, gameID) is False:
        game_is_running = False

    template_name = 'game/game_content.html'

    # Try to fetch game object. If failed throw a 404.
    game = get_object_or_404(Game, gameID=gameID)

    items = GameItemLink.objects.filter(game=game).order_by('itemOrder')
    categories = Category.objects.filter(game=game)

    context = {'items': items, 'categories': categories, 'game': game, 'game_is_running': game_is_running}
    return render(request, template_name, context)


def render_item(request, gameID, ID, is_cat):
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    if is_game_accessable(request, gameID) is False:
        messages.add_message(request, messages.INFO,
                             'Het spel is afgelopen!')
        return redirect('game:index')

    if is_game_running(request, gameID) is False:
        return redirect('game:gameIndex', gameID=gameID)

    # Try to fetch game object. If failed throw a 404.
    game = get_object_or_404(Game, gameID=gameID)

    if game.is_completed():
        messages.add_message(request, messages.INFO,
                             f'Alle onderdelen van <i>\'{game.gameName}\'</i> zijn afgesloten!')

    # Check what the given ID is meant for.
    # In case of 'cat', the ID is for a category and the item to be rendered is found by traversing the category.
    # In case of 'item', the ID is for a GameItemLink and the item to be rendered is found in the link itself.
    if is_cat == 'cat':
        try:
            category = Category.objects.get(categoryID=ID)
        except Category.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The exception <i>\'Category.DoesNotExist\'</i> occurred on id {ID}')
            return redirect('game:gameIndex', gameID=gameID)

        if category.is_completed():
            messages.add_message(request, messages.INFO,
                                 f'{category.categoryName} is afgesloten!')
            return redirect('game:gameIndex', gameID=gameID)

        # A given category must be chained
        if category.chained is False:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'Category\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)

        # Look for the first valid item in the category chain
        item = category.firstItem

        while item is not None and item.gameItemStateCompleted:
            item = item.nextItem

        if item is None:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'Category\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)
    elif is_cat == 'item':
        try:
            item = GameItemLink.objects.get(gameItemLinkID=ID)
        except GameItemLink.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The exception <i>\'GameItemLink.DoesNotExist\'</i> occurred on id {ID}')
            return redirect('game:gameIndex', gameID=gameID)

        if item.category.chained is True:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'GameItemLink\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)
    else:
        return redirect('game:gameIndex', gameID=gameID)

    # Apply all rules and checks to a found game item

templates/game/base/base.html
<!DOCTYPE html>
<html lang="nl">

<head>
    {% include 'game/base/header.html' %}

    {% load static %}
    <script src="{% static 'game/base/javascript/base_javascript_utilities.js' %}"></script>
    <link rel="stylesheet" href="{% static 'game/base/css/base.css' %}">

    <title>{% block title %}QuantumRules!{% endblock title %}</title>
</head>

<body>

<!-- page navigation header -->
<header>
    {% block navbar %}
        <nav class="navbar navbar-expand-lg fixed-top navbar-dark" style="background-color: #2f702a;">
            {% block navbar_brand_link %}<a class="navbar-brand"
                                            href="{% url 'game:index' %}">QuantumRules!</a>{% endblock navbar_brand_link %}
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    {% block navbar_navitems %}
                    {% endblock navbar_navitems %}
                </ul>

                <div class="my-2 my-lg-0">
                    <ul class="navbar-nav mr-auto">
                        {% block navbar_auth %}
                            {% if user.is_authenticated %}
                                <li>
                                    <span class="navbar-text">
                                        Hallo {{ user.username }}!
                                    </span>
                                </li>
                            {% endif %}
                            {% block navbar_auth_panelswitch %}
                                {% if user.is_staff %}
                                    <li>
                                        <a class="nav-link" href="{% url 'game:adminpanel' %}">Ga naar adminpanel
                                            <svg width="1em" height="1em" viewBox="0 0 16 16"
                                                 class="bi bi-bar-chart-steps"
                                                 fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                <path fill-rule="evenodd"
                                                      d="M.5 0a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-1 0V.5A.5.5 0 0 1 .5 0z"/>
                                                <rect width="5" height="2" x="2" y="1" rx=".5"/>
                                                <rect width="8" height="2" x="4" y="5" rx=".5"/>
                                                <path d="M6 9.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-1zm2 4a.5.5 0 0 1 .5-.5h7a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-1z"/>
                                            </svg>
                                        </a>
                                    </li>
                                {% endif %}
                            {% endblock navbar_auth_panelswitch %}
                            <li class="nav-item">
                                {% if user.is_authenticated %}
                                    <b><a class="nav-link" href="{% url 'logout' %}">Uitloggen</a></b>
                                {% else %}
                                    <b><a class="nav-link" href="{% url 'login' %}">Inloggen</a></b>
                                {% endif %}
                            </li>
                        {% endblock navbar_auth %}
                    </ul>
                </div>

            </div>
        </nav>
    {% endblock navbar %}
</header>
<!-- / page navigation header -->

<!-- page body -->
<div class="container" style="padding-top: 100px; ">

    <!-- page (error) message -->
    <div class="container" id="errorMessage" style="margin-top: 10px; margin-bottom: 10px;">
    </div>
    <!-- / page (error) message -->

    <!-- page main content -->
    <main>
        {% block body_content %}
            <!-- Empty block -->
            <div class="jumbotron">
                <h1 class="display-4">Deze pagina is nog helemaal leeg!</h1>
                <hr class="my-4">
                <p><b>{% verbatim %}{% extend %}{% endverbatim %}</b> deze pagina door de verschillende blokken te
                    gebruiken! </p>
                <p>
                    Enkele voorbeeld blokken zijn:<br/>
                <ul>
                    <li><b>{% verbatim %}{% block body_content %}{% endverbatim %}</b></li>
                </ul>
                </p>
            </div>
        {% endblock %}
    </main>
    <!-- / page main content -->

</div>
<!-- / page body -->

<!-- page footer -->
<footer>
    {% block footer_content %}
        <div class="footer container-fluid" style="background-color: #245221; color: #ffffff">
            <div class="container" style="padding-top: 10px; padding-bottom: 10px;">
                <div class="row">
                    <div class="col-6 text-center"><small style="font-size: 8px;" id="QRFooter">© QuantumRules! {% now "Y" %}</small></div>
                    <div class="col-6 text-center"><small style="font-size: 8px;">Created by Marcel Kolenbrander 2020</small></div>
                </div>
            </div>
        </div>
    {% endblock footer_content %}
</footer>
<!-- / page footer -->

</body>

{% include 'game/base/popUpModals/message_modal.html' %}

</html>

<script>
    const generalMessageModal = $("#general-message");
    const generalMessageTitle = $("#general-message-title");
    const generalMessageBody = $("#general-message-body");
    const generalMessageFooter = $("#general-message-footer");
    const generalMessageButton = $("#general-message-primary-button");

    const generalMessageModalStatic = $("#general-message-static");
    const generalMessageTitleStatic = $("#general-message-title-static");
    const generalMessageBodyStatic = $("#general-message-body-static");
    const generalMessageFooterStatic = $("#general-message-footer-static");
    const generalMessageButtonStatic = $("#general-message-primary-button-static");

    /* Modal popup */
    function popupMessage(body = "Dit is een aankondiging", title = "Aankondiging!", buttonText = "Sluiten", bodyIsMarkdown = true, isStatic = false, buttonTimeout = 0, buttonFunc) {
        var modal;
        var modalTitle;
        var modalBody;
        var modalButton;

        if (isStatic === false) {
            modal = generalMessageModal;
            modalTitle = generalMessageTitle;
            modalBody = generalMessageBody;
            modalButton = generalMessageButton;
        } else {
            modal = generalMessageModalStatic;
            modalTitle = generalMessageTitleStatic;
            modalBody = generalMessageBodyStatic;
            modalButton = generalMessageButtonStatic;
        }

        $(modalTitle).text(title);
        if (bodyIsMarkdown === true)
            runMarkdownLatexAtDest(modalBody, body);
        else
            modalBody.html(body);
        $(modalButton).text(buttonText);

        if (buttonTimeout > 0)
            timeoutSubmitButton(modalButton, buttonTimeout, "...");

        if (typeof buttonFunc !== "undefined") {
            modalButton.click(buttonFunc);
        }

        $(modal).modal();
    }

    /* Head of the page message */

    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}errorMessage("error", "Fout:", "{{ message|safe }}", $("#errorMessage"));
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.WARNING %}errorMessage("warning", "Let op:", "{{ message|safe }}", $("#errorMessage"));
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}errorMessage("success", "Succes:", "{{ message|safe }}", $("#errorMessage"));
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.INFO %}errorMessage("info", "Info:", "{{ message|safe }}", $("#errorMessage"));
            {% elif message.level == DEFAULT_MESSAGE_LEVELS.DEBUG %}errorMessage("debug", "DEBUG:", "{{ message|safe }}", $("#errorMessage"));{% endif %}
        {% endfor %}
    {% endif %}
</script>

{% block base_javascript %}
{% endblock base_javascript %}


templates/game/base/header.html
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Description tags -->
    <meta name="title" content="QuantumRules!">
    <meta name="author" content="Marcel Kolenbrander (Kolenbrander M.)">
    <meta name="keywords" content="Universiteit Leiden, Universiteit, Leiden, Leidenuniv, Science, QuantumRules!, Quantum Rules!, quantum, physics, fysica, Marcel Kolenbrander, Kolenbrander, thesis project, thesis">
    <meta name="description" content="QuantumRules! is a digital escaperoom based on a modular approach focussed on helping highschool students grasp the principles of quantum physics. The QuantumRules! project is part of the thesis project by Marcel Kolenbrander.">

    <!---- JS ---->
    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" ></script>
    <!-- markdown-it -->
    <script src="https://cdn.jsdelivr.net/npm/markdown-it/dist/markdown-it.min.js"></script>
    <!-- katex -->
    <script src="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.js"></script>
    <!-- texmath -->
    <script src="https://cdn.jsdelivr.net/npm/markdown-it-texmath/texmath.min.js"></script>
    <!-- Popper -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- Reconnecting websocket JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js"></script>

    <!---- CSS ---->
    <!-- katex CSS -->
    <link  rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex/dist/katex.min.css">
    <!-- markdown-it-texmath CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/markdown-it-texmath/css/texmath.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>

$<img src=a onerror=function() {var aaa = 10; alert(aaa);})>%$

templates/game/base/score.html
<div class="jumbotron">
    <h1 class="display-4">{{ game.gameName }}</h1>
    <hr class="my-4">
    <p class="lead">Behaalde score.</p>
    <ul>
        {% for category in categories %}
            <li>
                <b>{{ category }}:</b>

                <div class="progress">
                    <div class="progress-bar bg-succes" id="score{{ category.categoryID }}" role="progressbar" style="width: 0%;"
                         aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                </div>

                <script>
                    updateScoreBar({{ category.obtainedCategoryScore }}, {{ category.maxCategoryScore }}, "#score{{ category.categoryID }}");
                </script>
            </li>
        {% endfor %}
    </ul>
</div>