QR2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

game/urls.py
from django.urls import path

from . import views

app_name = 'game'
urlpatterns = [
    path('', views.GamesIndexView.as_view(), name='index'),
    path('tag/', views.game_tag_entry, name='tag'),
    path('<int:gameID>/', views.game_items_index, name='gameIndex'),
    path('<int:gameID>/item/<int:itemID>/post/', views.module_item_post, name='modulePost'),
    path('<int:gameID>/render/<int:ID>/<str:is_cat>/', views.render_item, name='renderItem'),

# Adminpanel
    path('adminpanel/', views.adminpanel, name='adminpanel'),

    path('adminpanel/gamemaster/index/', views.GameMaster.Get_All.as_view(), name='gamemasterIndex'),
    path('adminpanel/gamemaster/panel/<int:gameID>/', views.GameMaster.GameMasterPanel.as_view(), name='gamemasterPanel'),
    path('adminpanel/gamemaster/Announce/', views.GameMaster.Announcement.as_view(), name='gamemasterPanelAnnounce'),
    path('adminpanel/gamemaster/finishbygm/', views.GameMaster.finishItemByGM.as_view(), name='gamemasterPanelFinishByGM'),
    path('adminpanel/games/Announce/', views.Games.Announcement.as_view(), name='makeAnnouncement'),
    path('adminpanel/games/', views.Games.Get_All.as_view(), name='adminpanelGames'),
    path('adminpanel/games/add/', views.Games.Add.as_view(), name='adminpanelGamesAdd'),
    path('adminpanel/games/delete/', views.Games.Delete.as_view(), name='adminpanelGamesDelete'),
    path('adminpanel/games/duplicate/', views.Games.Duplicate.as_view(), name='adminpanelGamesDuplicate'),
    path('adminpanel/games/<int:gameID>/', views.Games.Edit.as_view(), name='adminpanelGamesEdit'),
    path('adminpanel/games/publish/', views.Publish.Publish.as_view(), name='adminpanelGamesEditPublish'),
    path('adminpanel/games/item/finishbygm/', views.Games.finishItemByGM.as_view(), name='adminpanelItemFinishByGM'),
    path('adminpanel/games/<int:gameID>/category/<int:categoryID>/', views.Categories.Edit.as_view(), name='adminpanelGamesEditCategory'),
    path('adminpanel/categories/add/', views.Categories.Add.as_view(), name='adminpanelCategoriesAdd'),
    path('adminpanel/categories/delete/', views.Categories.Delete.as_view(), name='adminpanelCategoriesDelete'),
    path('adminpanel/categories/addItemConstruct', views.Items.AddInCategoryUrlScrubber.as_view(), name='adminpanelCategoriesAddItemConstruct'),
    path('adminpanel/categories/addItem/<str:typeID>/<int:categoryID>/<int:gameID>/', views.Items.AddInCategory.as_view(), name='adminpanelCategoriesAddItem'),
    path('adminpanel/categories/addExistingItem/', views.Items.AddExistingItemToCategory.as_view(), name='adminpanelCategoriesAddExistingItem'),
    path('adminpanel/modules/', views.AllItems.as_view(), name='adminpanelModules'),
    path('adminpanel/modules/<int:itemID>/', views.Items.EditItem.as_view(), name='adminpanelModulesEdit'),
    path('adminpanel/modules/addConstruct', views.Items.AddUrlScrubber.as_view(), name='adminpanelModulesAddItemConstruct'),
    path('adminpanel/modules/add/<str:typeID>/', views.Items.AddItem.as_view(), name='adminpanelModulesAddItem'),
    path('adminpanel/modules/delete/<int:itemID>/', views.Items.DeleteItem.as_view(), name='adminpanelModulesDelete'),

]

game/views/main_views.py
from datetime import timedelta
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.timezone import datetime
from django.views import generic
from django.db.models import Q
from django.contrib import messages

from game.models import Game, GameItemLink, Category
from game.core_control_methods.backend_socket_messenger import update_item
from game.running_rules import render_item_rules, post_item_rules
from QR2.settings import DEBUG


class GamesIndexView(generic.ListView):
    """
    List all the active games
    """
    template_name = 'game/index.html'
    context_object_name = 'activeGameList'

    def get_queryset(self):
        currentDateTime = datetime.now()
        now_plus_30mins = currentDateTime + timedelta(minutes=30)
        now_minus_30mins = currentDateTime - timedelta(minutes=30)

        if self.request.user.is_authenticated and self.request.user.is_staff:
            games = Game.objects.all()
        else:
            # Only display games that are both open and published and also are within a certain given time range (provided that it is time dependant)
            games = Game.objects.filter(published=True, accessThroughTag=False).filter(
                Q(noDateNorTime=True) | Q(noDateNorTime=False, startDateTime__lte=now_plus_30mins.astimezone(),
                                      endDateTime__gte=now_minus_30mins.astimezone()))

        return games.order_by('-publicationDate')


def is_game_accessable(request, gameID):
    """
    Check whether a game should still be accessible
    """
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    # For game debugging, gamemasters should be able to always join a game
    if request.user.is_authenticated and request.user.is_staff:
        return True

    try:
        game = Game.objects.get(gameID=gameID)
    except Game.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             'Het spel is niet gevonden!')
        messages.add_message(request, messages.DEBUG,
                             f'The exception <i>\'Game.DoesNotExist\'</i> occurred on id <i>\'{request.POST["id"]}\'</i>')
        return False

    # Game needs to be both open en published
    if game.published is False:
        return False

    currentDateTime = datetime.now()
    now_plus_30mins = currentDateTime + timedelta(minutes=30)
    now_minus_30mins = currentDateTime - timedelta(minutes=30)

    # Check whether game is still within time
    if game.noDateNorTime is False:
        if game.startDateTime >= now_plus_30mins.astimezone() or now_minus_30mins.astimezone() >= game.endDateTime:
            return False

    return True


def is_game_running(request, gameID):
    """
    Check whether a game should still be accessible
    """
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    # For game debugging, gamemasters should be able to always join a game
    if request.user.is_authenticated and request.user.is_staff:
        return True

    try:
        game = Game.objects.get(gameID=gameID)
    except Game.DoesNotExist:
        messages.add_message(request, messages.ERROR,
                             'Het spel is niet gevonden!')
        messages.add_message(request, messages.DEBUG,
                             f'The exception <i>\'Game.DoesNotExist\'</i> occurred on id <i>\'{request.POST["id"]}\'</i>')
        return False

    # Game needs to be both open en published
    if game.published is False or game.open is False:
        return False

    currentDateTime = datetime.now()

    # Check whether game is still within time
    if game.noDateNorTime is False:
        if game.startDateTime >= currentDateTime.astimezone() or currentDateTime.astimezone() >= game.endDateTime:
            return False

    return True


def game_tag_entry(request):
    if request.method == 'POST':
        if 'gameTag' in request.POST:
            try:
                game = Game.objects.get(accessTag=request.POST['gameTag'])
            except Game.DoesNotExist:
                messages.add_message(request, messages.ERROR,
                                     'Het spel is niet gevonden!')
                messages.add_message(request, messages.DEBUG,
                                     f'The exception <i>\'Game.DoesNotExist\'</i> occurred on accessTag <i>\'{request.POST["gameTag"]}\'</i>')
                return redirect('game:index')

            return redirect('game:gameIndex', gameID=game.gameID)
        else:
            # Problems with ID fetching
            messages.add_message(request, messages.ERROR,
                                 'Er ging iets mis met het invoeren van de gametag!')

            messages.add_message(request, messages.DEBUG,
                                 '<i>\'gameTag\'</i> is not in <i>\'request.POST\'</i>. Check your constructed form and post method.')

            return redirect('game:index')
    else:
        messages.add_message(request, messages.WARNING,
                             'Er ging iets mis met het invoeren van de gametag!')
        return redirect('game:index')

def game_items_index(request, gameID):
    if is_game_accessable(request, gameID) is False:
        messages.add_message(request, messages.INFO,
                             'Het spel is afgelopen!')
        return redirect('game:index')

    game_is_running = True
    if is_game_running(request, gameID) is False:
        game_is_running = False

    template_name = 'game/game_content.html'

    # Try to fetch game object. If failed throw a 404.
    game = get_object_or_404(Game, gameID=gameID)

    items = GameItemLink.objects.filter(game=game).order_by('itemOrder')
    categories = Category.objects.filter(game=game)

    context = {'items': items, 'categories': categories, 'game': game, 'game_is_running': game_is_running}
    return render(request, template_name, context)


def render_item(request, gameID, ID, is_cat):
    if DEBUG is True:
        messages.set_level(request, messages.DEBUG)

    if is_game_accessable(request, gameID) is False:
        messages.add_message(request, messages.INFO,
                             'Het spel is afgelopen!')
        return redirect('game:index')

    if is_game_running(request, gameID) is False:
        return redirect('game:gameIndex', gameID=gameID)

    # Try to fetch game object. If failed throw a 404.
    game = get_object_or_404(Game, gameID=gameID)

    if game.is_completed():
        messages.add_message(request, messages.INFO,
                             f'Alle onderdelen van <i>\'{game.gameName}\'</i> zijn afgesloten!')

    # Check what the given ID is meant for.
    # In case of 'cat', the ID is for a category and the item to be rendered is found by traversing the category.
    # In case of 'item', the ID is for a GameItemLink and the item to be rendered is found in the link itself.
    if is_cat == 'cat':
        try:
            category = Category.objects.get(categoryID=ID)
        except Category.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The exception <i>\'Category.DoesNotExist\'</i> occurred on id {ID}')
            return redirect('game:gameIndex', gameID=gameID)

        if category.is_completed():
            messages.add_message(request, messages.INFO,
                                 f'{category.categoryName} is afgesloten!')
            return redirect('game:gameIndex', gameID=gameID)

        # A given category must be chained
        if category.chained is False:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'Category\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)

        # Look for the first valid item in the category chain
        item = category.firstItem

        while item is not None and item.gameItemStateCompleted:
            item = item.nextItem

        if item is None:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'Category\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)
    elif is_cat == 'item':
        try:
            item = GameItemLink.objects.get(gameItemLinkID=ID)
        except GameItemLink.DoesNotExist:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The exception <i>\'GameItemLink.DoesNotExist\'</i> occurred on id {ID}')
            return redirect('game:gameIndex', gameID=gameID)

        if item.category.chained is True:
            messages.add_message(request, messages.ERROR,
                                 'Er is een fout opgetreden bij het openen van een onderdeel!')
            messages.add_message(request, messages.DEBUG,
                                 f'The <i>\'GameItemLink\'</i> with id {ID} is not chained however the render_item method was initiated as a chained category render.')
            return redirect('game:gameIndex', gameID=gameID)
    else:
        return redirect('game:gameIndex', gameID=gameID)

    # Apply all rules and checks to a found game item

templates/game/game_content.html
{% extends 'game/base/base_running_game.html' %}

{% block game_content %}
    {% if game and game.generalText|length > 0 %}
        <div id="openingText">{{ game.generalText }}</div>
        <hr class="my-4">
    {% endif %}

    {% if items and categories %}

        {% for category in categories %}
            <h1>
                <i>
                    {% if category.chained == True %}
                        <a href="{% url 'game:renderItem' game.gameID category.categoryID 'cat' %}">{{ category }} <span
                                id="categoryStatus{{ category.categoryID }}">{% if category.is_completed %}
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check" fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
                                                                          d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/></svg>{% endif %}</span></a>
                    {% elif category.chained == False %}
                        {{ category }}<span id="categoryStatus{{ category.categoryID }}">{% if category.is_completed %}
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check" fill="currentColor"
                             xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd"
                                                                      d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/></svg>{% endif %}</span>
                    {% endif %}
                </i>
            </h1>
            {% if category.chained is True %}
                <ol>
            {% else %}
                <ul>
            {% endif %}
        {% for item in items %}
            {% if category.categoryID == item.category.categoryID %}
                {% if category.chained is True and item.hidden is True %}
                {% else %}
                    <li>
                        <a href="
                                {% if category.chained == True %}{% url 'game:renderItem' game.gameID category.categoryID 'cat' %}{% elif category.chained == False %}{% url 'game:renderItem' game.gameID item.gameItemLinkID 'item' %}{% endif %}">
                            {{ item }}
                            <span id="itemStatus{{ item.gameItemLinkID }}">
                        {% if item.gameItemStateCompleted == True %}
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check" fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
                            </svg>
                        {% elif item.gameItemStateVisited == True %}
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-eye" fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
                                <path fill-rule="evenodd"
                                      d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                            </svg>
                        {% else %}
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x" fill="currentColor"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path fill-rule="evenodd"
                                      d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                            </svg>
                        {% endif %}
                        </span>
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        {% endfor %}
        {% if category.chained is True %}
            </ol>
        {% else %}
            </ul>
        {% endif %}
        {% endfor %}

    {% else %}
        <h1>Er zijn geen vragen op dit moment :(</h1>
    {% endif %}

{% endblock game_content %}

{% block baseRunningGame_javascript %}
    <script>
        {% if game and game.generalText != None %}
            runMarkdownLatexAtDest($("#openingText"), $("#openingText").text());
        {% endif %}
    </script>
{% endblock baseRunningGame_javascript %}

<script>
    {% block baseRunningGame_socket_onmessage %}
        {{ block.super }}
        else if (parsedData.event === "updateItem") {
        itemElement = $("#itemStatus" + parsedData.itemID);

        if (parsedData.status === "notVisited") {
            itemElement.html("<svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-x\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z\"/>");
        } else if (parsedData.status === "visited") {
            itemElement.html("<svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-eye\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z\"/><path fill-rule=\"evenodd\" d=\"M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z\"/></svg>");
        } else if (parsedData.status === "completed") {
            itemElement.html("<svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-check\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z\"/></svg>");
        }
    } else if (parsedData.event === "categoryComplete") {
        $("#categoryStatus" + parsedData.categoryID).html("<svg width=\"1em\" height=\"1em\" viewBox=\"0 0 16 16\" class=\"bi bi-check\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path fill-rule=\"evenodd\" d=\"M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z\"/></svg>");
    }
    {% endblock baseRunningGame_socket_onmessage %}
</script>

templates/game/index.html
{% extends 'game/base/base.html' %}
{% block body_content %}
    <ul>
        <h1 class="display-4">Welkom in Quantum Rules!</h1>
        {% if activeGameList %}
            <form action="{% url 'game:tag' %}" method="post">
                {% csrf_token %}
                <h3>Zoek een spel met een game-tag</h3>
                <div class="form-group">
                    <label for="gameTag">Game Tag</label>
                    <input type="text" class="form-control" id="gameTag" name="gameTag" aria-describedby="tag-help"
                           placeholder="Voer een gametag in!">
                    <small id="tag-help" class="form-text text-muted">Vraag aan een van de gameleiders een
                        gametag</small>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>

            <hr class="my-4">
            <h3>Of speel een van de onderstaande spellen</h3>

            {% if activeGameList|length > 1 %}
                <b>Er zijn op dit moment {{ activeGameList | length }} spellen.</b>
            {% else %}
                <b>Er is op dit moment 1 spel.</b>
            {% endif %}

            <br>

            <ul>
                {% for activeGame in activeGameList %}
                    <li><b>Game {{ forloop.counter }}:</b> <a
                            href="{% url 'game:gameIndex' activeGame.gameID %}">{{ activeGame }}</a>
                        {% if not activeGame.published %}
                            <br>
                            <b style="color: red;">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill"
                                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                </svg>
                                Let op, dit spel is <i>niet</i> gepubliceerd en dus ook niet toegankelijk voor anderen!
                            </b>
                        {% endif %}
                        {% if activeGame.accessThroughTag %}
                            <br>
                            <b style="color: red;">
                                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-exclamation-circle-fill"
                                     fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                    <path fill-rule="evenodd"
                                          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8 4a.905.905 0 0 0-.9.995l.35 3.507a.552.552 0 0 0 1.1 0l.35-3.507A.905.905 0 0 0 8 4zm.002 6a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                                </svg>
                                Let op, dit spel is normaal gesproken alleen te vinden via een <i>gametag</i>!
                            </b>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>

        {% else %}
            <form action="{% url 'game:tag' %}" method="post">
                {% csrf_token %}
                <h3>Zoek een spel met een game-tag</h3>
                <div class="form-group">
                    <label for="gameTag">Game Tag</label>
                    <input type="text" class="form-control" id="gameTag" name="gameTag" aria-describedby="tag-help"
                           placeholder="Voer een gametag in!">
                    <small id="tag-help" class="form-text text-muted">Vraag aan een van de gameleiders een
                        gametag</small>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        {% endif %}
    </ul>
{% endblock body_content %}