QR2/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [
    path('', include('game.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

modules/models/baseModel.py
from django.db import models
from django.utils import timezone


class BaseModuleModel(models.Model):
    """
    This model is the base model the game requires to properly deal with modules.
    This needs to be inherited in the base/core data object in a module
    """
    # Mandatory fields!
    ID = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    has_hint = models.BooleanField(default=False)
    hint_content = models.TextField(null=True, blank=True)
    video_link = models.CharField(max_length=300, null=True, blank=True)

    publicationDate = models.DateTimeField(auto_now_add=True)
    lastChangedDate = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

templates/modules/superdenseModule/admin/add.html
{% extends 'game/gameAdminpanel/editadd_item.html' %}

{% block header_name %}
    Superdense Item Aanmaken
{% endblock header_name %}

{% block item_content %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
{% endblock item_content %}

{% block submit_button_content %}
    Item toevoegen
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus" fill="currentColor"
         xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
    </svg>
{% endblock submit_button_content %}

{% block baseAdminpanel_javascript %}
    <script>
        $(document).ready(function () {
            if (!$("#id_has_hint").is(":checked"))
                $("#div_id_hint_content").hide();

            $("#id_has_hint").click(function () {
                if ($(this).is(":checked"))
                    $("#div_id_hint_content").show();
                else
                    $("#div_id_hint_content").hide();
            })
        });

        $(document).ready(function () {
            liveTextUpdate($("#id_name"), $("#itemNameHeader"), "Text Item Aanmaken")
        });
    </script>
{% endblock baseAdminpanel_javascript %}

templates/modules/superdenseModule/admin/add_in_category.html
{% extends 'game/gameAdminpanel/category_add_item.html' %}

{% block header_name %}
    Superdense Item
{% endblock header_name %}

{% block new_item_content %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
{% endblock new_item_content %}

{% block baseAdminpanel_javascript %}
    <script>
    $(document).ready(function () {
        if(!$("#id_has_hint").is(":checked"))
            $("#div_id_hint_content").hide();

        $("#id_has_hint").click(function () {
            if($(this).is(":checked"))
                $("#div_id_hint_content").show();
            else
                $("#div_id_hint_content").hide();
        })
    });
    </script>
{% endblock baseAdminpanel_javascript %}

templates/modules/superdenseModule/admin/edit.html
{% extends 'game/gameAdminpanel/editadd_item.html' %}

{% block header_name %}
    {{ name }}
{% endblock header_name %}

{% block item_content %}
    {% load crispy_forms_tags %}
    {{ form|crispy }}
{% endblock item_content %}

{% block submit_button_content %}
    Item aanpassen
    <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill"
         fill="currentColor" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd"
              d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
    </svg>
{% endblock submit_button_content %}

{% block baseAdminpanel_javascript %}
    <script>
        $(document).ready(function () {
            if (!$("#id_has_hint").is(":checked"))
                $("#div_id_hint_content").hide();

            $("#id_has_hint").click(function () {
                if ($(this).is(":checked"))
                    $("#div_id_hint_content").show();
                else
                    $("#div_id_hint_content").hide();
            })
        });

        $(document).ready(function () {
            liveTextUpdate($("#id_name"), $("#itemNameHeader"), "{{ name }}")
        });
    </script>
{% endblock baseAdminpanel_javascript %}